### ISSUE TITLE
Cannot export wallets with non-ascii labels

### ISSUE THREAD

**Issue by hugeblank** [tmpim/KristWeb2#67]
Address labels containing anything non-ascii (kanji, etc.) will prevent the wallet export tool from outputting a string.

**Comment by signalhunter** [comment]
Screenshot:
![image](https://user-images.githubusercontent.com/9440126/227371271-ea43b03b-aee9-4664-8d6a-0327adf75e8b.png)

Error in JavaScript console:
```
Critical error:  DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
```
